version: "3"
services:
  fantasta_core:
    restart: "no"
    environment:
      - NODE_ENV=test
    volumes:
      #- ./coverage:/usr/fantasta_core/coverage
      - ./test:/usr/fantasta_core/test
    command: npm run start
    