version: "3"
services:
  fantasta_server:
    restart: "no"
    environment:
      - NODE_ENV=test
    volumes:
      - ./:/usr/fantasta_server/
      #- ./coverage:/usr/fantasta_server/coverage
    command: npm run start

  grafana:
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    