version: "3"

services:

  fantasta_mongo:
    container_name: fantasta_mongo
    image: mongo:4.4.2-bionic
    restart: always
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks: 
      -  default

  fantasta_server:
    container_name: fantasta_server
    image: fantasta_server:latest
    build:
       context: .
       dockerfile: Dockerfile
    restart: always
    # deploy:
    #   replicas: 1
    ports:
      - "3000:3000"
    networks: 
      -  default
    depends_on:
      - fantasta_mongo
    links:
      - fantasta_mongo
    #command: overwritten in the docker-compose.[environment].yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.24.1
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    deploy:
      replicas: 1
    ports:
      - "9090:9090"
    networks: 
      -  default
    links:
      - fantasta_server
    logging:
      driver: none

  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.7
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
    ports:
      - "3001:3000"
    networks: 
      -  default
    links:
      - prometheus
    logging:
      driver: none

volumes:
  mongodata:
    driver: local
  prometheus_data: {}
  grafana_data: {}