version: "3"
services:
  fantasta_server:
    environment:
      - NODE_ENV=test
    volumes:
      # - ./src:/usr/fantasta_server/src
      - ./test:/usr/fantasta_server/test
    # command: npm run prod
    command: bash -c "while true; do echo sleeping...; sleep 2; done"

  grafana:
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
