version: "3"
services:
  fantasta_server:
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/usr/fantasta_server/
    command: npm run debug

  grafana:
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin