version: "3"

services:

  fantastacore_mongo:
    container_name: fantastacore_mongo
    image: mongo:latest
    restart: always
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks: 
      -  default

  fantasta_core:
    container_name: fantasta_core
    image: fantasta_core:latest # use this image if already present in the local machine, build it otherwise
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    build: .
    restart: always
    # deploy:
    #   replicas: 1
    ports:
      - "3000:3000"
    networks: 
      -  default
    depends_on:
      - fantastacore_mongo
    links:
      - fantastacore_mongo
    #command: overwritten in the docker-compose.[environment].yml

volumes:
  mongodata:
    driver: local
