version: "3"
services:
  fantasta_server:
    restart: "no"
    environment:
      - NODE_ENV=test
    volumes:
      #- ./coverage:/usr/fantasta_server/coverage
      - ./test:/usr/fantasta_server/test
    command: npm run start
    