version: "3"
services:
  fantasta_server:
    restart: "no"
    environment:
      - NODE_ENV=test
    volumes:
      - ./:/usr/fantasta_server/
      #- ./coverage:/usr/fantasta_server/coverage
    command: npm run start
    