version: "3"

services:

  fantasta_mongo:
    container_name: fantasta_mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
    volumes:
      - mongodata:/data/db
    networks: 
      -  default

  fantasta_core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fantasta_core
    restart: always
    ports:
      - "3000:3000"
    networks: 
      -  default
    depends_on:
      - fantasta_mongo
    links:
      - fantasta_mongo
    #command: overwritten in the docker-compose.[environment].yml

volumes:
  mongodata:
    driver: local
