{
 "title": "Fantasta Server",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_connection_status_counter",
     "legendFormat": "mongoDB connection: {{status}}"
    }
   ]
  },
  { "title": "Load footballPlayers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Load footballPlayers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "load_footballPlayer_duration_seconds_sum{status=\"success\"}",
     "legendFormat": "load_footballPlayers - {{status}}"
    }
   ]
  },
  {
   "title": "Load footballPlayers (Error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load_footballPlayer_duration_seconds_count{status=\"error\"}",
     "legendFormat": "load_footballPlayers - {{status}}: {{msg}}"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "api_duration_seconds_sum{name=\"auth.delete\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    },
    {
     "expr": "api_duration_seconds_sum{name=\"auth.login\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    },
    {
     "expr": "api_duration_seconds_sum{name=\"auth.register\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    },
    {
     "expr": "api_duration_seconds_sum{name=\"auth.token\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    },
    {
     "expr": "api_duration_seconds_sum{name=\"auth.update\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    }
   ]
  },
  {
   "title": "Auth (Error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_duration_seconds_count{name=~\"auth.*\", status=\"error\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    }
   ]
  },
  { "title": "APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "FootballPlayer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "api_duration_seconds_sum{name=\"footballPlayer.get\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    }
   ]
  },
  {
   "title": "FootballPlayer (Payload)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "api_payload_bytes{name=\"footballPlayer.get\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "FootballPlayer (Error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_duration_seconds_count{name=~\"footballPlayer.*\", status=\"error\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    }
   ]
  },
  {
   "title": "League",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "api_duration_seconds_sum{name=\"league.create\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    },
    {
     "expr": "api_duration_seconds_sum{name=\"league.join\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    },
    {
     "expr": "api_duration_seconds_sum{name=\"league.present\", status=\"success\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    }
   ]
  },
  {
   "title": "League (Error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_duration_seconds_count{name=~\"league.*\", status=\"error\"}",
     "legendFormat": "{{name}} - {{status}} - {{msg}}"
    }
   ]
  }
 ]
}