{
 "title": "Nodejs Metrics",
 "description": "Nodejs runtime metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_requests", "legendFormat": "{{type}}" },
    { "expr": "nodejs_active_requests_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles", "legendFormat": "{{type}}" },
    { "expr": "nodejs_active_handles_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Nodejs Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "repeat": "service",
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Process start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "repeat": "service",
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "(process_start_time_seconds)*1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Metrics scrape duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "repeat": "service",
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "Process Heap",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "repeat": "service",
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "process_heap_bytes" }
   ]
  },
  {
   "title": "% CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[$interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total[$interval])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{service=\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "Event Loop Lag" }
   ]
  },
  {
   "title": "Max file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "process_max_fds" }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "External Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_external_memory_bytes", "legendFormat": "External Memory" }
   ]
  },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Total" },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual" }
   ]
  },
  { "title": "Heap Space Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes",
     "legendFormat": "{{space}}"
    }
   ]
  }
 ]
}