version: "3"

services:

  mongo:
    container_name: fantasta_mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks: 
      -  default

  fantasta_server:
    container_name: fantasta_core
    restart: always
    command: npm run start
    build: .
    ports:
      - "3001:3001"
    networks: 
      -  default
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  db_data:
    driver: local