
const Constants = {
    OK: "OK",
    NOT_FOUND: "NOT_FOUND",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    INT_SERV_ERR: "INT_SERV_ERR",
    WRONG_PASSWORD: "WRONG_PASSWORD",
    WRONG_USER: "WRONG_USER",
    FULL_LEAGUE: "FULL_LEAGUE",
    LEAGUE_NOT_FOUND: "LEAGUE_NOT_FOUND",
    USER_PRESENT: "USER_PRESENT",
    LEAGUE_PRESENT: "LEAGUE_PRESENT"
}

export { Constants }