
export const fakeUsers = [
	{
		username: "user01",
		email: "user01@email.com",
		password: "user01",
		leagues: []
	}, {
		username: "user02",
		email: "user02@email.com",
		password: "user02",
		leagues: []
	}, {
		username: "user03",
		email: "user03@email.com",
		password: "user03",
		leagues: []
	}, {
		username: "user04",
		email: "user04@email.com",
		password: "user04",
		leagues: []
	}, {
		username: "user05",
		email: "user05@email.com",
		password: "user05",
		leagues: []
	}, {
		username: "user06",
		email: "user06@email.com",
		password: "user06",
		leagues: []
	}, {
		username: "user07",
		email: "user07@email.com",
		password: "user07",
		leagues: []
	}, {
		username: "user08",
		email: "user08@email.com",
		password: "user08",
		leagues: []
	}, {
		username: "user09",
		email: "user09@email.com",
		password: "user09",
		leagues: []
	}, {
		username: "user10",
		email: "user10@email.com",
		password: "user10",
		leagues: []
	}
]


export const fakeTeams = [
	{
		name: "Inter",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Milan",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Juventus",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Barcellona",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Real Madrid",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Lazio",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Machester City",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Paris Saint-Germain",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Bayern Monaco",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Roma",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Atletico Madrid",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Cagliari",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Manchester United",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}, {
		name: "Ajax",
		footballPlayers: "",
		budget: "500",
		user: "",
		league: ""
	}
]


export const fakeLeagues = [
	{
		name: "Serie A",
		password: "seriea",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Serie B",
		password: "serieb",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Serie C",
		password: "seriec",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Serie D",
		password: "seried",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Eccellenza",
		password: "eccellenza",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Prima Categoria",
		password: "primacategoria",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Seconda Categoria",
		password: "secondacategoria",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Terza Categoria",
		password: "terzacategoria",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Premier League",
		password: "premierleague",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Bundesliga",
		password: "bundesliga",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Liga Spagnola",
		password: "ligaspagnola",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}, {
		name: "Ligue 1",
		password: "ligue1",
		admin: "",
		participants: 10,
		type: "classic",
		goalkeepers: 3,
		defenders: 8,
		midfielders: 8,
		strikers: 6,
		players: 25,
		budget: 500,
		countdown: 3,
		auctionType: "random",
		startPrice: "zero",
		teams: [],
		status: "new"
	}
]